export default [
  [{
    lowercaseRu: 'ё',
    lowercaseEn: '`',
    uppercaseRu: 'Ё',
    uppercaseEn: '`',
    keyCode: 'Backquote',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '1',
    lowercaseEn: '!',
    uppercaseRu: '1',
    uppercaseEn: '!',
    keyCode: 'Digit1',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '2',
    lowercaseEn: '"',
    uppercaseRu: '2',
    uppercaseEn: '"',
    keyCode: 'Digit2',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '3',
    lowercaseEn: '№',
    uppercaseRu: '3',
    uppercaseEn: '№',
    keyCode: 'Digit3',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '4',
    lowercaseEn: ';',
    uppercaseRu: '4',
    uppercaseEn: ';',
    keyCode: 'Digit4',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '5',
    lowercaseEn: '%',
    uppercaseRu: '5',
    uppercaseEn: '%',
    keyCode: 'Digit5',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '6',
    lowercaseEn: ':',
    uppercaseRu: '6',
    uppercaseEn: ':',
    keyCode: 'Digit6',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '7',
    lowercaseEn: '?',
    uppercaseRu: '7',
    uppercaseEn: '?',
    keyCode: 'Digit7',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '8',
    lowercaseEn: '*',
    uppercaseRu: '8',
    uppercaseEn: '*',
    keyCode: 'Digit8',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '9',
    lowercaseEn: '(',
    uppercaseRu: '9',
    uppercaseEn: '(',
    keyCode: 'Digit9',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '0',
    lowercaseEn: ')',
    uppercaseRu: '0',
    uppercaseEn: ')',
    keyCode: 'Digit0',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '-',
    lowercaseEn: '_',
    uppercaseRu: '-',
    uppercaseEn: '_',
    keyCode: 'Minus',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '=',
    lowercaseEn: '+',
    uppercaseRu: '=',
    uppercaseEn: '+',
    keyCode: 'Equal',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'Backspace',
    lowercaseEn: 'Backspace',
    uppercaseRu: 'Backspace',
    uppercaseEn: 'Backspace',
    keyCode: 'Backspace',
    specialty: 'specialKey',
  },
  ],
  [{
    lowercaseRu: 'Tab',
    lowercaseEn: 'Tab',
    uppercaseRu: 'Tab',
    uppercaseEn: 'Tab',
    keyCode: 'Tab',
    specialty: 'specialKey',
  },
  {
    lowercaseRu: 'й',
    lowercaseEn: 'q',
    uppercaseRu: 'Й',
    uppercaseEn: 'Q',
    keyCode: 'KeyQ',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'ц',
    lowercaseEn: 'w',
    uppercaseRu: 'Ц',
    uppercaseEn: 'W',
    keyCode: 'KeyW',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'у',
    lowercaseEn: 'e',
    uppercaseRu: 'У',
    uppercaseEn: 'E',
    keyCode: 'KeyE',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'к',
    lowercaseEn: 'r',
    uppercaseRu: 'К',
    uppercaseEn: 'R',
    keyCode: 'KeyR',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'е',
    lowercaseEn: 't',
    uppercaseRu: 'Е',
    uppercaseEn: 'T',
    keyCode: 'KeyT',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'н',
    lowercaseEn: 'y',
    uppercaseRu: 'Н',
    uppercaseEn: 'Y',
    keyCode: 'KeyY',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'г',
    lowercaseEn: 'u',
    uppercaseRu: 'Г',
    uppercaseEn: 'U',
    keyCode: 'KeyU',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'ш',
    lowercaseEn: 'i',
    uppercaseRu: 'Ш',
    uppercaseEn: 'I',
    keyCode: 'KeyI',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'щ',
    lowercaseEn: 'o',
    uppercaseRu: 'Щ',
    uppercaseEn: 'O',
    keyCode: 'KeyO',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'з',
    lowercaseEn: 'p',
    uppercaseRu: 'З',
    uppercaseEn: 'P',
    keyCode: 'KeyP',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'х',
    lowercaseEn: '[',
    uppercaseRu: 'Х',
    uppercaseEn: '{',
    keyCode: 'BracketLeft',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'ъ',
    lowercaseEn: ']',
    uppercaseRu: 'Ъ',
    uppercaseEn: '}',
    keyCode: 'BracketRight',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '\\',
    lowercaseEn: '\\',
    uppercaseRu: '/',
    uppercaseEn: '|',
    keyCode: 'Backslash',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'Del',
    lowercaseEn: 'Del',
    uppercaseRu: 'Del',
    uppercaseEn: 'Del',
    keyCode: 'Delete',
    specialty: 'specialKey',
  },
  ],
  [{
    lowercaseRu: 'CapsLock',
    lowercaseEn: 'CapsLock',
    uppercaseRu: 'CapsLock',
    uppercaseEn: 'CapsLock',
    keyCode: 'CapsLock',
    specialty: 'specialKey',
  },
  {
    lowercaseRu: 'ф',
    lowercaseEn: 'a',
    uppercaseRu: 'Ф',
    uppercaseEn: 'A',
    keyCode: 'KeyA',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'ы',
    lowercaseEn: 's',
    uppercaseRu: 'Ы',
    uppercaseEn: 'S',
    keyCode: 'KeyS',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'в',
    lowercaseEn: 'd',
    uppercaseRu: 'В',
    uppercaseEn: 'D',
    keyCode: 'KeyD',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'а',
    lowercaseEn: 'f',
    uppercaseRu: 'А',
    uppercaseEn: 'F',
    keyCode: 'KeyF',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'п',
    lowercaseEn: 'g',
    uppercaseRu: 'П',
    uppercaseEn: 'G',
    keyCode: 'KeyG',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'р',
    lowercaseEn: 'h',
    uppercaseRu: 'Р',
    uppercaseEn: 'H',
    keyCode: 'KeyH',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'о',
    lowercaseEn: 'j',
    uppercaseRu: 'О',
    uppercaseEn: 'J',
    keyCode: 'KeyJ',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'л',
    lowercaseEn: 'k',
    uppercaseRu: 'Л',
    uppercaseEn: 'K',
    keyCode: 'KeyK',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'д',
    lowercaseEn: 'l',
    uppercaseRu: 'Д',
    uppercaseEn: 'L',
    keyCode: 'KeyL',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'ж',
    lowercaseEn: ';',
    uppercaseRu: 'Ж',
    uppercaseEn: ':',
    keyCode: 'Semicolon',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'э',
    lowercaseEn: "'",
    uppercaseRu: 'Э',
    uppercaseEn: '"',
    keyCode: 'Quote',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'Enter',
    lowercaseEn: 'Enter',
    uppercaseRu: 'Enter',
    uppercaseEn: 'Enter',
    keyCode: 'Enter',
    specialty: 'specialKey',
  },
  ],
  [{
    lowercaseRu: 'Shift',
    lowercaseEn: 'Shift',
    uppercaseRu: 'Shift',
    uppercaseEn: 'Shift',
    keyCode: 'ShiftLeft',
    specialty: 'specialKey',
  },
  {
    lowercaseRu: 'я',
    lowercaseEn: 'z',
    uppercaseRu: 'Я',
    uppercaseEn: 'Z',
    keyCode: 'KeyZ',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'ч',
    lowercaseEn: 'x',
    uppercaseRu: 'Ч',
    uppercaseEn: 'X',
    keyCode: 'KeyX',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'с',
    lowercaseEn: 'c',
    uppercaseRu: 'С',
    uppercaseEn: 'C',
    keyCode: 'KeyC',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'м',
    lowercaseEn: 'v',
    uppercaseRu: 'М',
    uppercaseEn: 'V',
    keyCode: 'KeyV',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'и',
    lowercaseEn: 'b',
    uppercaseRu: 'И',
    uppercaseEn: 'B',
    keyCode: 'KeyB',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'т',
    lowercaseEn: 'n',
    uppercaseRu: 'Т',
    uppercaseEn: 'N',
    keyCode: 'KeyN',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'ь',
    lowercaseEn: 'm',
    uppercaseRu: 'Ь',
    uppercaseEn: 'M',
    keyCode: 'KeyM',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'б',
    lowercaseEn: ',',
    uppercaseRu: 'Б',
    uppercaseEn: '<',
    keyCode: 'Comma',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'ю',
    lowercaseEn: '.',
    uppercaseRu: 'Ю',
    uppercaseEn: '>',
    keyCode: 'Period',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '.',
    lowercaseEn: '/',
    uppercaseRu: ',',
    uppercaseEn: '?',
    keyCode: 'Slash',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '🠕',
    lowercaseEn: '🠕',
    uppercaseRu: '🠕',
    uppercaseEn: '🠕',
    keyCode: 'ArrowUp',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'Shift',
    lowercaseEn: 'Shift',
    uppercaseRu: 'Shift',
    uppercaseEn: 'Shift',
    keyCode: 'ShiftRight',
    specialty: 'specialKey',
  },
  ],
  [{
    lowercaseRu: 'Ctrl',
    lowercaseEn: 'Ctrl',
    uppercaseRu: 'Ctrl',
    uppercaseEn: 'Ctrl',
    keyCode: 'ControlLeft',
    specialty: 'specialKey',
  },
  {
    lowercaseRu: 'win',
    lowercaseEn: 'win',
    uppercaseRu: 'win',
    uppercaseEn: 'win',
    keyCode: 'MetaLeft',
    specialty: 'specialKey',
  },
  {
    lowercaseRu: 'Alt',
    lowercaseEn: 'Alt',
    uppercaseRu: 'Alt',
    uppercaseEn: 'Alt',
    keyCode: 'AltLeft',
    specialty: 'specialKey',
  },
  {
    lowercaseRu: ' ',
    lowercaseEn: ' ',
    uppercaseRu: ' ',
    uppercaseEn: ' ',
    keyCode: 'Space',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: 'AltGr',
    lowercaseEn: 'AltGr',
    uppercaseRu: 'AltGr',
    uppercaseEn: 'AltGr',
    keyCode: 'AltRight',
    specialty: 'specialKey',
  },
  {
    lowercaseRu: 'Ctrl',
    lowercaseEn: 'Ctrl',
    uppercaseRu: 'Ctrl',
    uppercaseEn: 'Ctrl',
    keyCode: 'ControlRight',
    specialty: 'specialKey',
  },
  {
    lowercaseRu: '🠔',
    lowercaseEn: '🠔',
    uppercaseRu: '🠔',
    uppercaseEn: '🠔',
    keyCode: 'ArrowLeft',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '🠗',
    lowercaseEn: '🠗',
    uppercaseRu: '🠗',
    uppercaseEn: '🠗',
    keyCode: 'ArrowDown',
    specialty: 'simpleKey',
  },
  {
    lowercaseRu: '🠖',
    lowercaseEn: '🠖',
    uppercaseRu: '🠖',
    uppercaseEn: '🠖',
    keyCode: 'ArrowRight',
    specialty: 'simpleKey',
  },
  // {
  //   lowercaseRu: '🠕',
  //   lowercaseEn: '🠕',
  //   uppercaseRu: '🠕',
  //   uppercaseEn: '🠕',
  //   keyCode: 'ArrowUp',
  //   specialty: 'simpleKey',
  // },
  ],
];
